name: hotgo-kafka-ui

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hotgo-kafka-ui
    restart: always
    environment:
      TZ: Asia/Shanghai
      KAFKA_CLUSTERS_0_NAME: hotgo-sasl-plain
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
    ports:
      - "18080:8080"
    networks:
      - kafka_sasl_plain

networks:
  kafka_sasl_plain:
    external: true
    name: hotgo-kafka-sasl-plain_app_network
