security.protocol=SSL
ssl.truststore.location=/opt/bitnami/kafka/config/certs/client.truststore.p12
ssl.truststore.password=changeit
ssl.truststore.type=PKCS12
ssl.keystore.location=/opt/bitnami/kafka/config/certs/client.keystore.p12
ssl.keystore.password=changeit
ssl.keystore.type=PKCS12
ssl.endpoint.identification.algorithm=
