Apollo:
  AppID: "hotgo"
  IP: "http://192.168.100.117:8080/"
  Cluster: "default"
  NamespaceName: "server.yaml"
  IsBackupConfig: true
  BackupConfigPath: "./apollo_config"
  Secret: ""
  SyncServerTimeout: 5000
  MustStart: true
  Watch: true

# 本地启动时 Apollo 客户端的日志配置
logger:
  apollo:
    path: "logs/apollo"
    level: "all"
    flags: 42
    file: "{Y-m-d}.log"
    stdoutColorDisabled: false
    writerColorEnable: false
    rotateExpire: "7d"
    rotateBackupLimit: 2
    rotateBackupCompress: 2
    format: "json"
    timeFormat: "2006-01-02T15:04:05Z07:00"

