Apollo:
  AppID: "hotgo"
  IP: "http://10.4.8.42:8080/"
  Cluster: "default"
  NamespaceName: "server.yaml"
  IsBackupConfig: true
  BackupConfigPath: "./apollo_config"
  Secret: ""
  SyncServerTimeout: 5000
  MustStart: true
  Watch: true
