// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// dataConnectorDao is the data access object for the table hg_data_connector.
// You can define custom methods on it to extend its functionality as needed.
type dataConnectorDao struct {
	*internal.DataConnectorDao
}

var (
	// DataConnector is a globally accessible object for table hg_data_connector operations.
	DataConnector = dataConnectorDao{internal.NewDataConnectorDao()}
)

// Add your custom methods and functionality below.
