// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// dataAgentDao is the data access object for the table hg_data_agent.
// You can define custom methods on it to extend its functionality as needed.
type dataAgentDao struct {
	*internal.DataAgentDao
}

var (
	// DataAgent is a globally accessible object for table hg_data_agent operations.
	DataAgent = dataAgentDao{internal.NewDataAgentDao()}
)

// Add your custom methods and functionality below.
