// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// dataFieldTemplateDao is the data access object for the table hg_data_field_template.
// You can define custom methods on it to extend its functionality as needed.
type dataFieldTemplateDao struct {
	*internal.DataFieldTemplateDao
}

var (
	// DataFieldTemplate is a globally accessible object for table hg_data_field_template operations.
	DataFieldTemplate = dataFieldTemplateDao{internal.NewDataFieldTemplateDao()}
)

// Add your custom methods and functionality below.
