// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// dataCleanTaskDao is the data access object for the table hg_data_clean_task.
// You can define custom methods on it to extend its functionality as needed.
type dataCleanTaskDao struct {
	*internal.DataCleanTaskDao
}

var (
	// DataCleanTask is a globally accessible object for table hg_data_clean_task operations.
	DataCleanTask = dataCleanTaskDao{internal.NewDataCleanTaskDao()}
)

// Add your custom methods and functionality below.
