// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// dataCleanStatDao is the data access object for the table hg_data_clean_stat.
// You can define custom methods on it to extend its functionality as needed.
type dataCleanStatDao struct {
	*internal.DataCleanStatDao
}

var (
	// DataCleanStat is a globally accessible object for table hg_data_clean_stat operations.
	DataCleanStat = dataCleanStatDao{internal.NewDataCleanStatDao()}
)

// Add your custom methods and functionality below.
