// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// dataFieldDao is the data access object for the table hg_data_field.
// You can define custom methods on it to extend its functionality as needed.
type dataFieldDao struct {
	*internal.DataFieldDao
}

var (
	// DataField is a globally accessible object for table hg_data_field operations.
	DataField = dataFieldDao{internal.NewDataFieldDao()}
)

// Add your custom methods and functionality below.
